train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 80
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 80
