train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 128
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        sample_rate: 16000
        p: 0.2
      - _target_: src.transforms.wav_augs.PitchShift
        sample_rate: 16000
        p: 0.2
      - _target_: src.transforms.wav_augs.RandomFade
        p: 0.2
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 128
